<nav class="navbar navbar-default navbar-transparent navbar-fixed-top navbar-burger" role="navigation">
    <!-- if you want to keep the navbar hidden you can add this class to the navbar "navbar-burger"-->
    <div class="container">
        <div class="navbar-header">
            <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar bar1"></span>
              <span class="icon-bar bar2"></span>
              <span class="icon-bar bar3"></span>
            </button>
            <a href="<?=_SITEROOT_;?>" class="navbar-brand">
              <img class="img-responsive" src="//shaktisociety.com/home/wp-content/uploads/2016/06/shaktilogo.png" alt="Shakti Society">
            </a>
        </div>
        <div class="collapse navbar-collapse" >
            <ul class="nav navbar-nav navbar-right navbar-uppercase">
                <li class="social-links">
                    <a href="https://www.facebook.com/events/940310892646407/" target="_blank">
                        <i class="fa fa-facebook-square"></i>
                    </a>
                    <a href="https://twitter.com/ShaktiSociety" target="_blank">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <!-- <a href="https://plus.google.com/+CreativetimPage">
                        <i class="fa fa-google-plus-square"></i>
                    </a>
                    <a href="https://dribbble.com/creativetim">
                        <i class="fa fa-dribbble"></i>
                    </a> -->

                </li>
                <li>
                    <a href="<?=_SITEROOT_;?>home">
                      Home
                    </a>
                </li>
                <li><a href="<?=_SITEROOT_;?>about/shakti-awards">Shakti Awards</a></li>
                <li class="has-sub">
                    <a>
                      About
                    </a>
                    <ul>
                      <li><a href="<?=_SITEROOT_;?>about/about-shakti-society">About Shakti Society</a></li>
                      <li><a href="<?=_SITEROOT_;?>about/nomination-form">Nomination Form</a></li>
                      <li><a href="<?=_SITEROOT_;?>about/gallery">Gallery</a></li>
                      <li><a href="<?=_SITEROOT_;?>about/sponsors">Sponsors</a></li>
                      <li><a href="<?=_SITEROOT_;?>about/vendors">Vendors</a></li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a>
                      Community Café
                    </a>
                    <ul>
                      <li><a href="<?=_SITEROOT_;?>community-cafe/about-community-cafe">About Community Cafe</a></li>
                      <li><a href="<?=_SITEROOT_;?>community-cafe/topic">Topic</a></li>
                      <li><a href="<?=_SITEROOT_;?>community-cafe/partners">Partners</a></li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a>
                      Wellness Day
                    </a>
                    <ul>
                      <li><a href="<?=_SITEROOT_;?>wellness-day/about-wellness-day">About Wellness Day</a></li>
                      <li><a href="<?=_SITEROOT_;?>wellness-day/sponsors">Sponsors</a></li>
                      <li><a href="<?=_SITEROOT_;?>wellness-day/vendors">Vendors</a></li>
                      <li><a href="<?=_SITEROOT_;?>wellness-day/gallery">Gallery</a></li>
                    </ul>
                </li>
                <li>
                    <a href="<?=_SITEROOT_;?>events">
                      Events
                    </a>
                </li>
                <li>
                    <a href="<?=_SITEROOT_;?>contact">
                    Contact
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
</nav>
